combine and fix logic

diff --git a/.github/workflows/deployStaging.yml b/.github/workflows/deployStaging.yml
--- a/.github/workflows/deployStaging.yml
+++ b/.github/workflows/deployStaging.yml
@@ -1,23 +1,34 @@
-name: DEPLOY Without Composer
+name: DEPLOY STAGING
 
 on:
-  # push:
-  #   branches: [main]
-  #   paths:
-  #     - 'frontend/**'
-  #     # Don't run if data pipeline services change; deployToTest.yml runs instead
-  #     - '!airflow/**'
-  #     - '!config/**'
-  #     - '!data/**'
-  #     - '!data_server/**'
-  #     - '!e2e_tests/**'
-  #     - '!exporter/**'
-  #     - '!frontend_server/**'
-  #     - '!python/**'
-  #     - '!requirements/**'
-  #     - '!run_gcs_to_bq/**'
-  #     - '!run_ingestion/**'
+  push:
+    branches: [main, infra-test]
+    paths:
+      # Run only if data pipeline services or the frontend/ changes
+      - 'airflow/**'
+      - 'config/**'
+      - 'data/**'
+      - 'data_server/**'
+      - 'e2e_tests/**'
+      - 'exporter/**'
+      - 'frontend_server/**'
+      - 'python/**'
+      - 'requirements/**'
+      - 'run_gcs_to_bq/**'
+      - 'run_ingestion/**'
+      - 'frontend/**'
   workflow_dispatch:
+    inputs:
+      branch:
+        description: 'Branch code to deploy'
+        default: 'main' #if not specified by the user
+        type: 'choice'
+        options:
+          - main
+          - infra-test
+
+env:
+  PIPELINE_CHANGED: false
 
 jobs:
   build-ingestion:
@@ -29,6 +40,8 @@ jobs:
     steps:
       - name: Check Out Code
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.branch || github.ref_name }}
       - id: auth
         uses: google-github-actions/auth@v2
         with:
@@ -52,6 +65,8 @@ jobs:
     steps:
       - name: Check Out Code
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.branch || github.ref_name }}
       - id: auth
         uses: google-github-actions/auth@v2
         with:
@@ -75,6 +90,8 @@ jobs:
     steps:
       - name: Check Out Code
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.branch || github.ref_name }}
       - id: auth
         uses: google-github-actions/auth@v2
         with:
@@ -98,6 +115,8 @@ jobs:
     steps:
       - name: Check Out Code
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.branch || github.ref_name }}
       - id: auth
         uses: google-github-actions/auth@v2
         with:
@@ -121,6 +140,9 @@ jobs:
     steps:
       - name: Check Out Code
         uses: actions/checkout@v4
+        # frontend code from 'main' even while testing pipeline changes via infra-test branch
+        with:
+          ref: main
       - id: auth
         uses: google-github-actions/auth@v2
         with:
@@ -138,6 +160,21 @@ jobs:
           basic-auth-username: ${{ secrets.BASIC_AUTH_USERNAME }}
           basic-auth-password: ${{ secrets.BASIC_AUTH_PASSWORD }}
 
+  check_for_pipeline_changes:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Check for Data Pipeline Changes
+        id: check_pipeline_changes
+        run: |
+          if git diff --quiet HEAD^ -- 'airflow/' 'config/' 'data/' \
+            'data_server/' 'e2e_tests/' 'exporter/' 'frontend_server/' \
+            'python/' 'requirements/' 'run_gcs_to_bq/' 'run_ingestion/'; then
+            echo "No changes found in data pipeline directories."
+          else
+            echo "Changes found in data pipeline directories."
+            echo "PIPELINE_CHANGED=true" >> $GITHUB_ENV
+          fi
   deploy:
     if: github.repository == 'SatcherInstitute/health-equity-tracker'
     name: Deploy to Test Environment
@@ -149,11 +186,14 @@ jobs:
         build-exporter,
         build-data-server,
         build-frontend,
+        check_for_pipeline_changes,
       ]
 
     steps:
       - name: Check Out Code
         uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.inputs.branch || github.ref_name }}
       - id: auth
         uses: google-github-actions/auth@v2
         with:
@@ -190,8 +230,7 @@ jobs:
           -var 'gcs_to_bq_image_digest=${{ needs.build-gcs-to-bq.outputs.image-digest }}' \
           -var 'data_server_image_digest=${{ needs.build-data-server.outputs.image-digest }}' \
           -var 'exporter_image_digest=${{ needs.build-exporter.outputs.image-digest }}' \
-          -var 'frontend_image_digest=${{ needs.build-frontend.outputs.image-digest }}' \
-          -var 'include_composer=false'
+          -var 'frontend_image_digest=${{ needs.build-frontend.outputs.image-digest }}'
 
           data_server_url=$(terraform output data_server_url)
           echo "data_server_url=$data_server_url" >> "$GITHUB_OUTPUT"
@@ -203,6 +242,46 @@ jobs:
           echo "exporter_url=$exporter_url" >> "$GITHUB_OUTPUT"
           frontend_url=$(terraform output frontend_url)
           echo "frontend_url=$frontend_url" >> "$GITHUB_OUTPUT"
+
+        # only run this step if pipeline files were changed
+      - name: Composer / Airflow Environment Variables
+        if: ${{ env.PIPELINE_CHANGED == 'true' }}
+        id: airflow-environment-variables
+        run: |
+          ENVIRONMENT_NAME=data-ingestion-environment
+          LOCATION=us-central1
+          BUCKET="us-central1-data-ingestion-bucket-${{ secrets.TEST_PROJECT_ID }}"
+
+          if ! gcloud composer environments describe $ENVIRONMENT_NAME --location=$LOCATION &>/dev/null; then
+            echo "INFRA-TEST Composer environment does not exist. Creating..."
+            gcloud composer environments create $ENVIRONMENT_NAME --location=$LOCATION --storage-bucket=$BUCKET
+          else
+            echo "INFRA-TEST Composer environment already exists."
+          fi
+
+          echo "Waiting for Composer environment to be in RUNNING state... this can take up to 40 minutes."
+          while [[ "$(gcloud composer environments describe $ENVIRONMENT_NAME --location=$LOCATION --format='value(state)')" != "RUNNING" ]]; do
+            sleep 10
+          done
+          echo "INFRA-TEST Composer environment is now in RUNNING state."
+
+          gcloud composer environments update $ENVIRONMENT_NAME \
+          --update-env-variables=AIRFLOW_VAR_DUMMY=${{ github.run_id }} \
+          --update-env-variables=AIRFLOW_VAR_INGEST_TO_GCS_SERVICE_ENDPOINT=${{ steps.terraform.outputs.ingestion_url }} \
+          --update-env-variables=AIRFLOW_VAR_GCS_TO_BQ_SERVICE_ENDPOINT=${{ steps.terraform.outputs.gcs_to_bq_url }} \
+          --update-env-variables=AIRFLOW_VAR_EXPORTER_SERVICE_ENDPOINT=${{ steps.terraform.outputs.exporter_url }} \
+          --update-env-variables=AIRFLOW_VAR_GCS_LANDING_BUCKET=msm-test-landing-bucket \
+          --update-env-variables=AIRFLOW_VAR_GCS_MANUAL_UPLOADS_BUCKET=msm-test-manual-data-bucket \
+          --location=$LOCATION
+
+        # only run this step if pipeline files were changed
+      - name: Upload Airflow DAGs and utility file
+        if: ${{ env.PIPELINE_CHANGED == 'true' }}
+        working-directory: ./airflow
+        run: |
+          ./upload-dags.sh
+
+        # always finish with testing connection between data server and frontend
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
